### ISSUE TITLE
it seems plugin creaters friends are abusing the functions of the plugin

### ISSUE THREAD

**Issue by oschaotic** [DMWatch/DMWatch#9]
it seems plugin creaters friends are abusing the functions of the plugin so far multiple people have been reported via the plugin ruining their online credability without suffiecent evidence some even as far as ruining their credability for their online buissness affecting merch sales

**Comment by briby222** [comment]
what the fuck does this mean LOL

**Comment by oschaotic** [comment]
exactly what the title would describe
 however i havnt been able to contact the creator for comment
